# This workflow automatically compiles the anthology document

name: compile-anthology

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository on runner
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: ./compile_tex
      - name: Commit and push this change
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "[CI] Upload generated PDF"
